"""Mock agent implementation for testing and dry-run mode."""

from collections.abc import AsyncIterator

from gh_worker.agents.base import AgentEvent, AgentEventType, AgentResult, BaseAgent


class MockAgent(BaseAgent):
    """Mock agent that uses base implementations for testing/dry-run mode."""

    @property
    def name(self) -> str:
        """Return the agent name."""
        return "mock"

    @property
    def requires_cli(self) -> bool:
        """Return whether this agent requires an external CLI tool."""
        return False

    async def plan(
        self, issue_content: str, repository_path: str
    ) -> AgentResult:
        """Generate an implementation plan for an issue (mock implementation).

        Args:
            issue_content: The full issue description
            repository_path: Path to the cloned repository

        Returns:
            AgentResult with the generated mock plan
        """
        # Mock plan implementation for testing/fallback
        mock_plan = f"""# Implementation Plan (Mock)

This is a mock plan generated by the mock agent implementation.
Use a real agent (e.g., claude-code) for actual plan generation.

## Issue Summary
{issue_content[:200]}{'...' if len(issue_content) > 200 else ''}

## Steps
1. Analyze the issue requirements
2. Design the solution
3. Implement the changes
4. Add tests
5. Update documentation

## Files to Modify
- TBD

## Testing Strategy
- Unit tests
- Integration tests

---
*Generated by mock agent implementation*
"""
        return AgentResult(
            success=True,
            output=mock_plan,
            metadata={"mock": True, "agent": self.name},
        )

    async def implement(
        self,
        issue_content: str,
        plan_content: str,
        repository_path: str,
        issue_number: int,
        branch_name: str,
    ) -> AsyncIterator[AgentEvent]:
        """Implement the plan (mock implementation).

        Args:
            issue_content: The full issue description
            plan_content: The generated plan
            repository_path: Path to the cloned repository
            issue_number: Issue number
            branch_name: Branch to create for the implementation

        Yields:
            AgentEvent objects as the implementation progresses
        """
        yield AgentEvent(
            type=AgentEventType.ERROR,
            content="Mock agent does not support implementation. Use a real agent for implementation.",
            metadata={"agent": "mock", "issue_number": issue_number},
        )

    async def commit(
        self,
        repository_path: str,
        issue_number: int,
        branch_name: str,
    ) -> AsyncIterator[AgentEvent]:
        """Commit changes (mock implementation).

        Args:
            repository_path: Path to the cloned repository
            issue_number: Issue number
            branch_name: Branch name

        Yields:
            AgentEvent objects as the commit progresses
        """
        yield AgentEvent(
            type=AgentEventType.ERROR,
            content="Mock agent does not support committing. Use a real agent for committing.",
            metadata={"agent": "mock", "issue_number": issue_number},
        )

    async def monitor(self, session_id: str) -> AsyncIterator[AgentEvent]:
        """Monitor an ongoing agent session (mock implementation).

        Args:
            session_id: The session ID to monitor

        Yields:
            AgentEvent objects from the session
        """
        yield AgentEvent(
            type=AgentEventType.ERROR,
            content="Mock agent does not support monitoring. Use a real agent for monitoring.",
            metadata={"agent": "mock", "session_id": session_id},
        )
